---
title: "Data preperation"
output: html_document
date: '2022-07-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}

pacman::p_load(tidyverse, here, psych, gmodels)


```


```{r, warning=FALSE, message=FALSE}
Data <- read_csv(here('Data\\Data.csv'))

```


```{r, warning=FALSE, message=FALSE}
replaceMETI <- function(data, Condition, goodChar){
  
  if((Condition == 'brownKnow' & goodChar == TRUE) | (Condition == 'blueKnow' & goodChar == FALSE)){
  
  data <- if_else(data == 'Analyst Blue', 7,
                  if_else(data == ')))', 6,
                          if_else(data == '))', 5,
                                  if_else(data == '()', 4,
                                          if_else(data == '(((', 3,
                                                  if_else(data == '((', 2,
                                                          if_else(data == 'Analyst Brown', 1, NA_real_,)))))))
  
}else if((Condition == 'brownKnow' & goodChar == FALSE) | (Condition == 'blueKnow' & goodChar == TRUE)){
  
  data <- if_else(data == 'Analyst Blue', 1,
                  if_else(data == ')))', 2,
                          if_else(data == '))', 3,
                                  if_else(data == '()', 4,
                                          if_else(data == '(((', 5,
                                                  if_else(data == '((', 6,
                                                          if_else(data == 'Analyst Brown', 7, NA_real_,)))))))
  
 

}
   return(data)
}
```


```{r, warning=FALSE, message=FALSE}
brownKnow <- Data %>% 
  filter(Condition == 'brownKnow')


brownKnow <- brownKnow %>% 
mutate(METI_1_2 = replaceMETI(METI_1_2, Condition = 'brownKnow', goodChar = TRUE),
       METI_1_4 = replaceMETI(METI_1_4, Condition = 'brownKnow', goodChar = TRUE),
       METI_1_7 = replaceMETI(METI_1_7, Condition = 'brownKnow', goodChar = TRUE),
       METI_1_8 = replaceMETI(METI_1_8, Condition = 'brownKnow', goodChar = TRUE),
       METI_2_1 = replaceMETI(METI_2_1, Condition = 'brownKnow', goodChar = TRUE),
       METI_2_2 = replaceMETI(METI_2_2, Condition = 'brownKnow', goodChar = TRUE),
       METI_2_4 = replaceMETI(METI_2_4, Condition = 'brownKnow', goodChar = TRUE),
       METI_2_6 = replaceMETI(METI_2_6, Condition = 'brownKnow', goodChar = TRUE),
       METI_2_7 = replaceMETI(METI_2_7, Condition = 'brownKnow', goodChar = TRUE),
       
       
       METI_1_1 = replaceMETI(METI_1_1, Condition = 'brownKnow', goodChar = FALSE),
       METI_1_3 = replaceMETI(METI_1_3, Condition = 'brownKnow', goodChar = FALSE),
       METI_1_5 = replaceMETI(METI_1_5, Condition = 'brownKnow', goodChar = FALSE),
       METI_1_6 = replaceMETI(METI_1_6, Condition = 'brownKnow', goodChar = FALSE),
       METI_2_3 = replaceMETI(METI_2_3, Condition = 'brownKnow', goodChar = FALSE),
       METI_2_5 = replaceMETI(METI_2_5, Condition = 'brownKnow', goodChar = FALSE),
       METI_2_8 = replaceMETI(METI_2_8, Condition = 'brownKnow', goodChar = FALSE)) %>% 
  mutate(marketUnderstanding = if_else(marketUnderstanding == '1 - Not at all', 1,
                                       if_else(marketUnderstanding == '7 - Very familiar', 7, as.numeric(marketUnderstanding)))) %>%
  mutate(faceDecision = if_else(faceDecisionBlue == 'IM_b1V9prTO1mcx6PX', 'Nice', 'notNice')) %>% 
  mutate(DV_1 = if_else(DV_1 == 'Analyst Brown', 'prefereKnow', 'prefereDK'),
         DV_2 = if_else(DV_2 == 'Analyst Blue', 'prefereKnow', 'prefereDK')) %>%
  mutate(changeDV = if_else(DV_1 == 'prefereKnow' & DV_2 == 'prefereKnow', 'prefereKnow',
                            if_else(DV_1 == 'prefereDK' & DV_2 == 'prefereDK', 'prefereDK',
                                    if_else(DV_1 == 'prefereDK' & DV_2 == 'prefereKnow', 'change_To_Know',
                                            'change_To_DK')))) %>% 
  mutate(whoErrors = if_else(whoErrors == 'Analyst Brown', 'knowError',
                             if_else(whoErrors == 'Analyst Blue', 'DKError', whoErrors)))



blueKnow <- Data %>% 
  filter(Condition == 'blueKnow')


blueKnow <- blueKnow %>% 
mutate(METI_1_2 = replaceMETI(METI_1_2, Condition = 'blueKnow', goodChar = TRUE),
       METI_1_4 = replaceMETI(METI_1_4, Condition = 'blueKnow', goodChar = TRUE),
       METI_1_7 = replaceMETI(METI_1_7, Condition = 'blueKnow', goodChar = TRUE),
       METI_1_8 = replaceMETI(METI_1_8, Condition = 'blueKnow', goodChar = TRUE),
       METI_2_1 = replaceMETI(METI_2_1, Condition = 'blueKnow', goodChar = TRUE),
       METI_2_2 = replaceMETI(METI_2_2, Condition = 'blueKnow', goodChar = TRUE),
       METI_2_4 = replaceMETI(METI_2_4, Condition = 'blueKnow', goodChar = TRUE),
       METI_2_6 = replaceMETI(METI_2_6, Condition = 'blueKnow', goodChar = TRUE),
       METI_2_7 = replaceMETI(METI_2_7, Condition = 'blueKnow', goodChar = TRUE),
       
       
       METI_1_1 = replaceMETI(METI_1_1, Condition = 'blueKnow', goodChar = FALSE),
       METI_1_3 = replaceMETI(METI_1_3, Condition = 'blueKnow', goodChar = FALSE),
       METI_1_5 = replaceMETI(METI_1_5, Condition = 'blueKnow', goodChar = FALSE),
       METI_1_6 = replaceMETI(METI_1_6, Condition = 'blueKnow', goodChar = FALSE),
       METI_2_3 = replaceMETI(METI_2_3, Condition = 'blueKnow', goodChar = FALSE),
       METI_2_5 = replaceMETI(METI_2_5, Condition = 'blueKnow', goodChar = FALSE),
       METI_2_8 = replaceMETI(METI_2_8, Condition = 'blueKnow', goodChar = FALSE)) %>% 
  mutate(marketUnderstanding = if_else(marketUnderstanding == '1 - Not at all', 1,
                                       if_else(marketUnderstanding == '7 - Very familiar', 7, as.numeric(marketUnderstanding)))) %>%
  mutate(faceDecision = if_else(faceDecisionBrown == 'IM_b1V9prTO1mcx6PX', 'Nice', 'notNice')) %>% 
  mutate(DV_1 = if_else(DV_1 == 'Analyst Blue', 'prefereKnow', 'prefereDK'),
         DV_2 = if_else(DV_2 == 'Analyst Blue', 'prefereKnow', 'prefereDK')) %>%
    mutate(changeDV = if_else(DV_1 == 'prefereKnow' & DV_2 == 'prefereKnow', 'prefereKnow',
                            if_else(DV_1 == 'prefereDK' & DV_2 == 'prefereDK', 'prefereDK',
                                    if_else(DV_1 == 'prefereDK' & DV_2 == 'prefereKnow', 'change_To_Know',
                                            'change_To_DK')))) %>% 
  mutate(whoErrors = if_else(whoErrors == 'Analyst Blue', 'knowError',
                             if_else(whoErrors == 'Analyst Brown', 'DKError', whoErrors)))


Data <- rbind(brownKnow, blueKnow) %>% 
  mutate(METI = rowMeans(cbind(METI_1_1, METI_1_2, METI_1_3, METI_1_4, METI_1_5, METI_1_6, METI_1_7, METI_1_8, METI_2_1, METI_2_2, METI_2_3, METI_2_4, METI_2_5, METI_2_6, METI_2_7, METI_2_8)))

```


```{r, warning=FALSE, message=FALSE}
intelectualUmility <- function(data, Reverse = FALSE){
  
    if(Reverse == TRUE){
  
  data <- if_else(data == 'Strongly Disagree', 7,
                  if_else(data == 'Disagree', 6,
                          if_else(data == 'Slightly disagree', 5,
                                  if_else(data == 'Neither agree nor disagree', 4,
                                          if_else(data == 'Slightly agree', 3,
                                                  if_else(data == 'Agree', 2,
                                                          if_else(data == 'Strongly agree', 1, NA_real_)))))))
  
}else{
  
 data <- if_else(data == 'Strongly Disagree', 1,
                  if_else(data == 'Disagree', 2,
                          if_else(data == 'Slightly disagree', 3,
                                  if_else(data == 'Neither agree nor disagree', 4,
                                          if_else(data == 'Slightly agree', 5,
                                                  if_else(data == 'Agree', 6,
                                                          if_else(data == 'Strongly agree', 7, NA_real_)))))))
  
 

}
   return(data)
  
}

Data <- Data %>% 
  mutate(IH_1 = intelectualUmility(IH_1, Reverse = TRUE),
         IH_2 = intelectualUmility(IH_2),
         IH_3 = intelectualUmility(IH_3),
         IH_4 = intelectualUmility(IH_4),
         IH_5 = intelectualUmility(IH_5, Reverse = TRUE),
         IH_6 = intelectualUmility(IH_6, Reverse = TRUE)) %>% 
  mutate(IH = rowMeans(cbind(IH_1, IH_2, IH_3, IH_4, IH_5, IH_6)))

```



```{r, warning=FALSE, message=FALSE}
Data <- Data %>% 
  filter(Consecutively == 'Yes') %>% 
  filter(Disturbances == 'No') %>% 
  filter(Alone == 'Alone') %>% 
  filter(Honesty == 'Yes, I put in a reasonable effort') %>% 
  filter(Duration < 20) %>% 
  filter(!Q1 %in% c('58ed2be2a083320001a13783', '5c1450b06d1ac90001028a2a', '62ce01e10103af1a049c6b31')) %>% 
  filter((whoNotKnow == 'Analyst Brown' & Condition == 'blueKnow') | (whoNotKnow == 'Analyst Blue' & Condition == 'brownKnow'))
```

```{r, warning=FALSE, message=FALSE}
write.csv(Data, 'dataForAnalysis.csv')
```
